name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Firebase
        working-directory: ../
        run: firebase deploy --only hosting:default --token ${{ secrets.FIREBASE_TOKEN }}
